# -*- coding: utf-8 -*-
"""project108.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jFSaIRdJzzw_lKU9DX2v9Z0h13kwfQxD
"""

import csv
import pandas as pd
import plotly.figure_factory as ff


df=pd.read_csv('project108data.csv')
print(df)

fig=ff.create_distplot([df["Avg Rating"].tolist()],["Result"],show_hist=False)
print(df['Avg Rating'].tolist())
fig.show()